# Generated by Django 5.1.7 on 2025-03-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=8)),
                ('product_category', models.TextField(max_length=2048)),
                ('product_subcategory', models.TextField(max_length=2048)),
                ('product_name', models.TextField(max_length=2048)),
                ('product_price', models.CharField(max_length=8)),
                ('task_media', models.FileField(blank=True, upload_to='uploaded_files')),
                ('task_background_media', models.FileField(blank=True, upload_to='uploaded_files')),
            ],
        ),
    ]
