# Generated by Django 5.2 on 2025-04-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0003_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
