# Generated by Django 5.2 on 2025-04-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_remove_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='https://sandbox.iyzi.link/AAENhA'),
        ),
    ]
