# Generated by Django 5.1.7 on 2025-04-10 09:56

import console.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='task_background_media',
            field=models.FileField(blank=True, upload_to=console.models.product_media_upload_to),
        ),
        migrations.AlterField(
            model_name='product',
            name='task_media',
            field=models.FileField(blank=True, upload_to=console.models.product_media_upload_to),
        ),
    ]
