# Generated by Django 5.1.7 on 2025-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_alter_product_task_background_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='task_background_media',
            field=models.FileField(blank=True, upload_to='uploaded_files'),
        ),
        migrations.AlterField(
            model_name='product',
            name='task_media',
            field=models.FileField(blank=True, upload_to='uploaded_files'),
        ),
    ]
