# Generated by Django 5.1.7 on 2025-04-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0008_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
